### ISSUE TITLE
Múltiplos erros em cpu.v 

### ISSUE THREAD

**Issue by daniel-pg** [izumizawa/mc851#8]
Adicionei essa issue só pra lembrar das coisas que tem que resolver na branch main, mas acho que o Paulo já está resolvendo na branch reg-id-ex.

A saber:
- wb_data está declarado como wire de 1 bit (deveria ser reg de 32 bits)
- Módulo "alu_module" não encontrado (o módulo alu_module deveria se chamar só alu, ou o alu.v deveria virar alu_module.v, um dos dois)
- idex_imm precisa passar pela extensão de sinal antes de ser salvo nos registradores de pipeline.

**Comment by paulopacitti** [comment]
Conserto isso no #9
